# Generated by Django 4.2 on 2023-04-23 11:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_catalog_product_cat'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalog',
            options={'ordering': ('name',), 'verbose_name': 'Категорию', 'verbose_name_plural': 'Каталог'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ('title',), 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
    ]
