# Generated by Django 4.2 on 2023-05-12 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_likedproduct_options_cartproduct'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartproduct',
            options={'ordering': ('user',), 'verbose_name': 'Корзина', 'verbose_name_plural': 'Корзина'},
        ),
        migrations.AddField(
            model_name='product',
            name='search_names',
            field=models.TextField(blank=True),
        ),
    ]
